name: immunityunity

on:
  workflow_dispatch:
  schedule:
    - cron: '46 20 * * *'

jobs:
  run-immunityunity:
    runs-on: macOS-10.15
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.6.3'
          
      - name: Restore R package cache
        id: cache-r-packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('install-packages.R') }}-2
          
      - name: Install packages
        if: steps.cache-r-packages.outputs.cache-hit != 'true'        
        run: R -e 'source("install-packages.R", echo = TRUE)'
        
      - name: Download Parse and Tweet
        run: Rscript vax.R
        
      # Add new files in data folder, commit along with other modified files, push
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
